"""Add eneable lock config

Revision ID: 02da9defb758
Revises: 058f9d946a86
Create Date: 2023-03-22 10:51:06.144188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02da9defb758'
down_revision = '058f9d946a86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('enableLock', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixtures', 'enableLock')
    # ### end Alembic commands ###
