"""Add test description

Revision ID: 0c8c5702da0b
Revises: de25e7470885
Create Date: 2023-03-14 18:12:16.173264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8c5702da0b'
down_revision = 'de25e7470885'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('description', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'description')
    # ### end Alembic commands ###
