"""Add fixture status log

Revision ID: 49396c222215
Revises: 963495d264c9
Create Date: 2023-04-17 12:38:49.324356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49396c222215'
down_revision = '963495d264c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixture_status_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixtureId', sa.Integer(), nullable=True),
    sa.Column('fixtureIp', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('seconds', sa.Integer(), nullable=True),
    sa.Column('timeStampStart', sa.TIMESTAMP(), nullable=True),
    sa.Column('timeStampEnd', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fixture_status_logs')
    # ### end Alembic commands ###
