"""Add fixture abort test

Revision ID: 963495d264c9
Revises: c681db10315a
Create Date: 2023-04-17 09:38:20.811460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '963495d264c9'
down_revision = 'c681db10315a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('abortTest', sa.Boolean(), nullable=True))
    op.alter_column('fixtures', 'mode',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fixtures', 'mode',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('fixtures', 'abortTest')
    # ### end Alembic commands ###
