"""Add Catalog Items

Revision ID: 9f2dacaaa5f3
Revises: b68af0abaa71
Create Date: 2023-05-15 15:19:37.693863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f2dacaaa5f3'
down_revision = 'b68af0abaa71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(length=256), nullable=True),
    sa.Column('value', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalog_items')
    # ### end Alembic commands ###
