"""Add test fullPath

Revision ID: a15291c68df0
Revises: a6ab9b8e37b1
Create Date: 2023-02-27 09:06:11.562537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a15291c68df0'
down_revision = 'a6ab9b8e37b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('fullPath', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'fullPath')
    # ### end Alembic commands ###
