"""Fixture disabled

Revision ID: a6ab9b8e37b1
Revises: ca0b5f200202
Create Date: 2023-02-25 10:46:42.347990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6ab9b8e37b1'
down_revision = 'ca0b5f200202'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('isDisabled', sa.Boolean(), nullable=True))
    op.drop_column('fixtures', 'areLastTestPass')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('areLastTestPass', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('fixtures', 'isDisabled')
    # ### end Alembic commands ###
