"""Add employees and settings

Revision ID: b68af0abaa71
Revises: d063cab9613d
Create Date: 2023-05-12 12:40:49.495810

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b68af0abaa71'
down_revision = 'd063cab9613d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('encryptedPassword', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('text', sa.String(length=256), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('tests', 'traceability')
    op.drop_column('tests', 'countInYield')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('countInYield', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('tests', sa.Column('traceability', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_table('settings')
    op.drop_table('employees')
    # ### end Alembic commands ###
