"""Add test mode

Revision ID: c3cde4c9cad2
Revises: 02da9defb758
Create Date: 2023-04-10 12:49:56.398769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3cde4c9cad2'
down_revision = '02da9defb758'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('mode', sa.Integer(), default=0))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'mode')
    # ### end Alembic commands ###
