"""Initial

Revision ID: ca0b5f200202
Revises: 
Create Date: 2023-02-23 17:53:06.857240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0b5f200202'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('areLastTestPass', sa.Boolean(), nullable=True),
    sa.Column('isSkipped', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serialNumber', sa.String(length=512), nullable=True),
    sa.Column('project', sa.String(length=512), nullable=True),
    sa.Column('startTime', sa.DateTime(), nullable=True),
    sa.Column('endTime', sa.DateTime(), nullable=True),
    sa.Column('codeVersion', sa.String(length=512), nullable=True),
    sa.Column('fixtureIp', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('stepLabel', sa.String(length=512), nullable=True),
    sa.Column('operator', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tests')
    op.drop_table('fixtures')
    # ### end Alembic commands ###
