"""Add sync columns

Revision ID: d063cab9613d
Revises: 117f1504ed6c
Create Date: 2023-04-20 16:07:28.600462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd063cab9613d'
down_revision = '117f1504ed6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixture_status_logs', sa.Column('isSync', sa.Boolean(), nullable=True))
    op.add_column('fixtures', sa.Column('isSync', sa.Boolean(), nullable=True))
    op.add_column('maintenance', sa.Column('isSync', sa.Boolean(), nullable=True))
    op.add_column('tests', sa.Column('isSync', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'isSync')
    op.drop_column('maintenance', 'isSync')
    op.drop_column('fixtures', 'isSync')
    op.drop_column('fixture_status_logs', 'isSync')
    # ### end Alembic commands ###
