"""Add Online Mode

Revision ID: d3e177d8a802
Revises: a15291c68df0
Create Date: 2023-02-28 13:38:18.474458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e177d8a802'
down_revision = 'a15291c68df0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('isRetestMode', sa.Boolean(), nullable=True))
    op.add_column('tests', sa.Column('isOnlineMode', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'isOnlineMode')
    op.drop_column('fixtures', 'isRetestMode')
    # ### end Alembic commands ###
