"""Add yield and upload to sfc

Revision ID: de25e7470885
Revises: d3e177d8a802
Create Date: 2023-02-28 16:31:44.946146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de25e7470885'
down_revision = 'd3e177d8a802'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('countInYield', sa.Boolean(), nullable=True))
    op.add_column('tests', sa.Column('uploadToSFC', sa.Boolean(), nullable=True))
    op.drop_column('tests', 'isOnlineMode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('isOnlineMode', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('tests', 'uploadToSFC')
    op.drop_column('tests', 'countInYield')
    # ### end Alembic commands ###
