"""Add fixture temp

Revision ID: ff88529d4209
Revises: 9f2dacaaa5f3
Create Date: 2023-11-22 10:34:28.761025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff88529d4209'
down_revision = '9f2dacaaa5f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixture_temp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixtureId', sa.Integer(), nullable=True),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('timeStamp', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fixture_temp')
    # ### end Alembic commands ###
